name: kuki_proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^9.2.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Funcion2Fig12.png
    - assets/images/Logito.png
    - assets/images/Logito2.png
    - assets/images/perfil1.jpeg
    - assets/images/ganadero.png
    - assets/images/pesquero.png
    - assets/images/construccion.png
    - assets/images/agricultor.png
    - assets/images/madera.jpeg
    - assets/images/plasticos.jpeg
    - assets/images/conchas.jpeg
    - assets/images/birrete.png
    - assets/images/panufacturero.png
    - assets/images/alpaca.jpg
    - assets/images/composta.jpg
    - assets/images/red.png
    - assets/images/huesos.jpg
    - assets/images/tablaroca.jpg
    - assets/images/escombros.jpg
    - assets/images/verdura.jpg
    - assets/images/composta_hojas.jpg
    - assets/images/fibra.jpg
    